name: Update build date on merge

on:
  push:
    branches:
      - main

permissions:
    contents: write

jobs:
  update-build-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{secrets.KR_GUARDIAN_ACCESS_TOKEN}}

      - name: Set build date
        run: |
          DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "BUILD_DATE=$DATE" > buildinfo.txt

      - name: Commit and push build date
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "kr-guardian"
          git config user.email "info@kuhn-ruess.de"
          git add buildinfo.txt
          git commit -m "Update build date [skip ci]" || echo "No changes"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
